import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import { Provider } from "react-redux";
import {store} from "@/store/store";
import CustomProvider from "@/store/provider";
const inter = Inter({ subsets: ["latin"] });
import 'bootstrap/dist/css/bootstrap.css';

export const metadata: Metadata = {
  title: "Notedly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <CustomProvider>
            <NavBar />
            {children}
          </CustomProvider>
        </body>
      </html>
    </>
  );
}
